conda installation for apple silicon requires numpy=1.20.3 and python=3.9
Workaround for 'AttributeError: Module 'numpy._core' has no attribute 'defchararray'' error when using numpy-2.2.3 - found via https://github.com/numpy/numpy/issues/20748